### ISSUE TITLE
Multi-Webhook Support

### ISSUE THREAD

**Issue by mashwishi** [barelyaiden/discode#3]
Let's say you don't own one server to share code right?
It would be great if there's multiple webhook with a method like

1. `>discode: Add new webhook` 
2. `>discode: Enter name`
3. `>discode: Enter url`
4. `>discode: Enter author`
5. `>discode: Enter avatar`

**Preview:**
![image](https://user-images.githubusercontent.com/62344860/127760476-bfd09b8c-5022-4f05-b473-7a8f8e4c2d1b.png)

**Comment by barelyaiden** [comment]
Will look into implementing it! Very likely will not add more than one button for sharing code in the context menu as to not add unnecessary bloat. Might ask the user which webhook they would like to share to when they want to share and any alternative webhooks will be added in via extension settings. For now I will make it only support 3 webhooks as dynamically doing it is not possible at the moment.

**Comment by barelyaiden** [comment]
Added in release 2.0.1
